name: mongodb_standalone

services:

  mongosh:
    image: alpine/mongosh
    container_name: standalone_mongosh
    command: tail -f /dev/null
    networks:
      - mongodb_network

  database:
    image: mongodb/mongodb-enterprise-server:8.0.5-ubuntu2204
    command: --bind_ip_all
    container_name: standalone_mongodb
    volumes:
      - mongodb_vol:/data/db
    networks:
      - mongodb_network

networks:
  mongodb_network:

volumes:
  mongodb_vol:
